//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraSimulation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFileTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFileTitle() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CameraSimulation.Properties.ResourceFileTitle", typeof(ResourceFileTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AimLeftSpeed 的本地化字符串。
        /// </summary>
        internal static string AimLeftSpeed {
            get {
                return ResourceManager.GetString("AimLeftSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AimRightSpeed 的本地化字符串。
        /// </summary>
        internal static string AimRightSpeed {
            get {
                return ResourceManager.GetString("AimRightSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AimServoAngle 的本地化字符串。
        /// </summary>
        internal static string AimServoAngle {
            get {
                return ResourceManager.GetString("AimServoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AimSpeed 的本地化字符串。
        /// </summary>
        internal static string AimSpeed {
            get {
                return ResourceManager.GetString("AimSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurAccelX 的本地化字符串。
        /// </summary>
        internal static string CurAccelX {
            get {
                return ResourceManager.GetString("CurAccelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurAccelY 的本地化字符串。
        /// </summary>
        internal static string CurAccelY {
            get {
                return ResourceManager.GetString("CurAccelY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurLeftPWM 的本地化字符串。
        /// </summary>
        internal static string CurLeftPWM {
            get {
                return ResourceManager.GetString("CurLeftPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurLeftSpeed 的本地化字符串。
        /// </summary>
        internal static string CurLeftSpeed {
            get {
                return ResourceManager.GetString("CurLeftSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurRightPWM 的本地化字符串。
        /// </summary>
        internal static string CurRightPWM {
            get {
                return ResourceManager.GetString("CurRightPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurRightSpeed 的本地化字符串。
        /// </summary>
        internal static string CurRightSpeed {
            get {
                return ResourceManager.GetString("CurRightSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurServoAngle 的本地化字符串。
        /// </summary>
        internal static string CurServoAngle {
            get {
                return ResourceManager.GetString("CurServoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurServoPWM 的本地化字符串。
        /// </summary>
        internal static string CurServoPWM {
            get {
                return ResourceManager.GetString("CurServoPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FrameInform 的本地化字符串。
        /// </summary>
        internal static string FrameInform {
            get {
                return ResourceManager.GetString("FrameInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageHeight 的本地化字符串。
        /// </summary>
        internal static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageInform 的本地化字符串。
        /// </summary>
        internal static string ImageInform {
            get {
                return ResourceManager.GetString("ImageInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageThreshold 的本地化字符串。
        /// </summary>
        internal static string ImageThreshold {
            get {
                return ResourceManager.GetString("ImageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageWdith 的本地化字符串。
        /// </summary>
        internal static string ImageWdith {
            get {
                return ResourceManager.GetString("ImageWdith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RodeType 的本地化字符串。
        /// </summary>
        internal static string RodeType {
            get {
                return ResourceManager.GetString("RodeType", resourceCulture);
            }
        }
    }
}
